apiVersion: apps/v1
metadata: 
  name: simple-app
kind: Deployment
spec: 
  selector:
    matchLabels:
      app: simple-app 
  template:   
    metadata:
      labels: 
        app: simple-app
    spec:
      containers: 
      - name: simple-app
        image: theoafactor/app_deploy_test:2
        ports: 
        - containerPort: 80